name: Build Test

on:
  push:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: example/HelloWindow.sln
  
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Dump Env 1 (Windows)
      shell: cmd
      run: set

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Find Visual Studio Root
      run: |
        $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
        echo "VS_PATH=$vsPath" >> $env:GITHUB_ENV

    - name: Dump Env 2 (Windows)
      shell: cmd
      run: set

    - name: Directory List
      shell: cmd
      run: |
        c:
        cd "Program Files\Microsoft Visual Studio\18\Enterprise"
        dir
        echo done

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Build MFC Project
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} /p:configuration="${{ env.BUILD_CONFIGURATION }}" /p:platform="${{ env.BUILD_PLATFORM }}"
